_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
            "3":
                - 2
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.10
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
base_model:
    value:
        name: ViT-B-32
        weights: laion2b_s34b_b79k
data:
    value:
        data_dir: ./data
        num_workers: 0
        pin_memory: false
helip:
    value:
        alpha: 0.25
        cache_embeddings: true
        enabled: true
        k: 5
        lambda_hnml: 0.5
        mining_freq: 5
        p: 20
input:
    value:
        size:
            - 224
            - 224
trainer:
    value:
        batch_size: 4
        checkpoint_dir: ./checkpoints
        cocoop:
            ctx_init: ""
            n_ctx: 8
            prec: fp16
        epochs: 3
        lr: 0.002
        patience: 5
        warmup_epochs: 1
        weight_decay: 0.05
